version: "3"
services:
  db:
    image: postgres:11
    container_name: auth-postgres
    ports:
      - 8111:5432
    volumes:
      - dbdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: auth
  redis:
    image: redis:4.0
    container_name: auth-redis
    ports:
      - 8112:6379
    environment:
      REDIS_PASSWORD: password
volumes:
  dbdata:
