version: "3"
services:
  auth:
    image: auth-app
    container_name: auth-app
    ports:
      - 5000:5000
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - redis
    environment:
      GOPATH: '/go'
  postgres:
    image: postgres:11
    container_name: auth-postgres
    ports:
      - 8111:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: auth
  redis:
    image: redis:4.0
    container_name: auth-redis
    ports:
      - 8112:6379
    command: redis-server --requirepass password
    volumes:
      - redis_data:/data
volumes:
  postgres_data:
  redis_data:
