default: &default
  addr: localhost:5000
  sql:
    host: localhost:8111
    db: auth
    user: root
  redis:
    host: localhost:8112
    db: 0
    conn_timeout: 10s
    oper_timeout: 3s
  token:
    access_ttl: 720h
    refresh_ttl: 4464h # 6 month
  env:
    # Secrets
    AUTH_SQL_PASSWORD: password
    AUTH_REDIS_PASSWORD:
    AUTH_JWT_SECRET: secret