default: &default
  addr: localhost:5000
  sql:
    host: localhost:8111
    db: auth
    user: root
  token:
    access_ttl: 720h
    refresh_ttl: 4464h # 6 month
  env:
    # Secrets
    AUTH_SQL_PASSWORD: password